### ISSUE TITLE
Transitions support

### ISSUE THREAD

**Issue by BennyHinrichs** [spaceavocado/svelte-router#1]
Sorry to be peppering you with questions. Is there any support for transitions between routes, like https://github.com/alshdavid/crayon? Looks like they do it via applying and removing classes. However, I like your method of doing the `<RouterLink to="/">` component better than their method of `<button on:click={() => nav.navigate('/')}>`.

This is probably beyond the scope, but shared element transitions would be cool too: https://dev.to/buhrmi/svelte-component-transitions-5ie

**Comment by davidhorak** [comment]
@BennyHinrichs this is quite tricky on the component level, as svelte handles transitions on DOM elements. But it quite simple to add your own overlay transition elements. The [svelte-router-template](https://github.com/spaceavocado/svelte-router-template) is now updated with a simple fadein transition example. Please see the updated [Live Preview](https://spaceavocado.github.io/svelte-router-template/).

The transition is handled here: https://github.com/spaceavocado/svelte-router-template/blob/master/src/js/app.svelte.

**Comment by BennyHinrichs** [comment]
That's definitely better than nothing 👍

I'm still pretty new to Svelte, but I'll try to noodle on it. Perhaps it could be passed on route creation

```javascript
{ 
  path: '/users/:id(\\d+)',
  name: 'USER_PROFILE',
  component: ViewUserProfile,
  animations: [
    {
      // general animation
      type: 'transition',
      fn: fade,
    }, {
      // route-specific animation
      type: 'transition',
      fn: fly,
      value: '{ y: 100%, duration: 300 }',
      to: '/users',
      from: '/users'
    },
  ],
}
```

Then the `<svelte:component>` in `/component/view.svelte` could be wrapped in a div with the animations applied. Might have to use `onBeforeNavigation` and a second temporary, absolutely positioned div, maybe with `animate:flip`? One of the problems is that you can't fill it with reactive variables (I don't think). If you wanted to update it, you'd have to create a special method to do just that.

**Comment by ansarizafar** [comment]
@davidhorak  check these links for svelte page transitions.
https://dev.to/buhrmi/svelte-component-transitions-5ie
https://github.com/pngwn/svelte-travel-transitions

**Comment by davidhorak** [comment]
@BennyHinrichs both of those examples uses the transition on the DOM elements in view components it selves. The template repository is now updated to illustrate this approach. 

~~There is a caveat we will try to address:~~
- ~~The out transition applied on the view will break the view change, so the view components must use in transitions only for now. This is related to how svelte manages the changed component in the directive <svelte:component> we have dig deep to figure out how to wait for the transition/animation end before changing the view component.~~

Regarding the passed animations route setup, we will explore his option.

**Comment by BennyHinrichs** [comment]
Okay, so they're currently on each view component itself. Got it. This is my basic idea for doing multiple pages:

1. Route navigation to new view (NV) is triggered
1. Current view (CV) `boundingClientRectangle` is queried
1. CV, which is inside a container div, sends its dimensions to container div
1. Container div is absolutely positioned
1. NV is loaded into its destiny location with `opacity` 0 (or `translateY` 100% or what have you)
1. Transition out class is applied to CV, transition in class is removed from NV
1. CV is disposed of

Something like that. What do you think?

Although I do wonder if we could do `out:send` and `in:receive` with a `crossfade` between container divs for CV and NV. I think the problem with that is you couldn't do different transitions between routes. It'd all be the same.

**Comment by davidhorak** [comment]
I guess in general the issue is that the Svelte transitions/animations are not designed in the way, as for example in the Vue Transition, where the transition is the controller of inner elements. In the Svelte world, the transition is directly on the DOM element. 

So in other words, this is the current approach: https://svelte.dev/repl/23645f07be66497f90707d82827d2911?version=3.8.1

But this does not work:
https://svelte.dev/repl/afa8d517bffb40e59a6c256b644ee900?version=3.8.1

One ideal would be a custom transition element, similiar to Vue, to handle the transition target node.
