### ISSUE TITLE
RouterLink does not output attributes passed

### ISSUE THREAD

**Issue by taviks** [spaceavocado/svelte-router#10]
With the following code:

```html
<RouterLink to="{{name: 'ABOUT'}}" class="navItem">About</RouterLink>
```

The class `navItem` is not passed to the generated `a` tag. In the console there's a message from `link.svelte:86` that state: `<Link> was created with unknown prop 'class'</Link>`. 

So it seems that handling for passing through attributes is missing(?).

**Comment by davidhorak** [comment]
@yet-another-dev it is actually "**cls**" prop, https://github.com/spaceavocado/svelte-router#router-link-component, to pass the custom base class.

**Comment by taviks** [comment]
Ah, I see... Missed that in the docs. 

Would it not be more intuitive/flexible to simply pass through all props (via `{...$$props}` [documented here](https://svelte.dev/docs#Attributes_and_props))

> `$$props` references all props that are passed to a component – including ones that are not declared with `export`.

That would allow other attributes to pass through without having to manually handle them. It would also allow for not having to use a custom "class" attribute for passing through classes (which becomes unnecessarily verbose when using Pug, as it requires declaring the actual attribute rather than being able to use Put's dot syntax (e.g. `RouterLink.navItem(to=")`).

Looks like adding `{...$$props}` here should do the trick (though I haven't tested this yet): https://github.com/spaceavocado/svelte-router/blob/8358e4b49126f34bf7e66a92c89e8ebf7171aad2/component/link.svelte#L89-L94

The only reason I can see to potentially not want to do this is due to the note on the docs that states: 

> It is useful in rare cases, but not generally recommended, as it is difficult for Svelte to optimize.

The "as it is difficult for Svelte to optimize" is the part that makes me think this might be undesired for some reason. But without knowing more about the details of the optimizations that this makes difficult for Svelte it's hard to say.

**Comment by davidhorak** [comment]
@yet-another-dev Using the $$props is definitely an option but it the case of the Link component is rather more safe from the perspective of shared library to have a limited, and documented, set of properties - which we might extend as needed by community. 

Also, the link component should be more/less just a base link component, for any project specific needs it would be better to create a custom component with own props, or use the custom component as a wrapper of the shipped Link component.
