### ISSUE TITLE
Callbacks: "to, from" versus "from, to"

### ISSUE THREAD

**Issue by BennyHinrichs** [spaceavocado/svelte-router#2]
In some places in the docs, e.g. `onNavigationChanged` you say that the callback params are `(to, from)`, and then in other places, e.g. `/component/view.svelte:58`, you say it's `(from, to)`. Which one is it? When I run `onNavigationChanged`, it looks like `(from, to)` to me.

**Comment by davidhorak** [comment]
@BennyHinrichs it is fn(from, to) for onNavigationChanged, onBeforeNavigation - the documentation has been updated.

**Comment by BennyHinrichs** [comment]
Excellent. I think it's still the old one in `src/router.js:124,143`.

**Comment by davidhorak** [comment]
@BennyHinrichs Good catch, all update in a5c1b6181f0d736729236c8582d7d7c6cc11c148 commit.
