### ISSUE TITLE
Prevent Navigation on select child elements

### ISSUE THREAD

**Issue by BennyHinrichs** [spaceavocado/svelte-router#3]
Tell me what you think of this. In `link.svelte`, change line 73 to

```javascript
on:click|preventDefault="{(e) => !e.target.closest('.preventNavigation') && navigate(to)}"
```

That gives us the ability to mark certain elements to not trigger nav. I don't know if this affects performance at all.

In my case, I have a list of link cards. Most of the card should navigate on click, but there are interactive elements on the cards.

**Comment by davidhorak** [comment]
@BennyHinrichs that would be too rigid, so rather, please see the latest version, 1.0.12, there is new Link component prop called "disabled' - https://github.com/spaceavocado/svelte-router#router-link-component

If set to true, the navigation actions is disabled on the link and the underlying <a> element has set "disabled" css class.

**Comment by BennyHinrichs** [comment]
Can you explain how that would be used here so that no navigation happens when you click "Don't Navigate":

```html
<RouterLink to="/">
  <div>Navigate</div>
  <div class="no-navigation">Don't Navigate</div>
</RouterLink>
```

**Comment by davidhorak** [comment]
Now I see your point better.

This would just disable the whole element:
```
<RouterLink to="/" disabled={true}>
  <div>Navigate</div>
  <div class="no-navigation">Don't Navigate</div>
</RouterLink>
```

In your case, it would be better to create your own link component. The bare minimum is to just leverage ```$router.routeURL(to)``` to get the URL in the case of location object, and than call ```$router.push(to)``` based on your logic.

**Comment by BennyHinrichs** [comment]
Sorry, I meant how can I make it so clicking "Navigate" follows the link, but clicking "Don't Navigate" does nothing? Won't your example make it so no navigation happens on both divs?

**Comment by davidhorak** [comment]
Updated the comment above.

**Comment by davidhorak** [comment]
Or you can wrap the link into your own DOM structure, e.g.:
```
<div class="link">
   <RouterLink to="/" disabled={true}>Navigate</RouterLink>
   <div class="no-navigation">Don't Navigate</div>
</div>
```

**Comment by BennyHinrichs** [comment]
I might look into making my own component. Consider the following case where you have an interactive element in the middle of the click area:

```html
<RouterLink to="/route">
  <div>Click to Navigate!</div>

  <label class="no-navigation">
    <input type="checkbox">
    Click Without Navigating!
  </label>

  <div>Click to Navigate!</div>
</RouterLink>
```

Okay, after some thought, what about adding a `disabledClass` property to router link component? Then `navigate(event)` in `link.svelte` would be expanded with

```javascript
if (disabledClass && event.target.closest('.' + disabledClass) {
  return;
}
```

**Comment by davidhorak** [comment]
I see what you want to achieve but it is too specific to be considered as general usage - there might be plenty of cases like that, so the custom component seems to be the suitable, project specific approach here.

Quick tip, you prevent the event triggering like so:

```
<script>
  import Link from './Link.svelte';
  function noop() {}
</script>

<Link>
  <div>Click to Navigate!</div>
  <label class="no-navigation" on:click|preventDefault|stopPropagation={noop}>
    Click Without Navigating!
  </label>
</Link>
```

**Link.svelte:**
```
<script>
  function click() {
    console.log('click');
  }
</script>

<a href="/" on:click|preventDefault={click}>
  <slot></slot>
</a>
```

**Comment by BennyHinrichs** [comment]
Wow, I'm dumb. I totally forgot that `stopPropagation` exists :smile: That actually solves the whole problem still using `RouterLink`. Thanks for indulging me.

**Comment by davidhorak** [comment]
@BennyHinrichs no worries, glad to help.
