### ISSUE TITLE
Support for Analytics like Matomo

### ISSUE THREAD

**Issue by UIX-Design** [spaceavocado/svelte-router#7]
I want to integrate Matomo in my Svelte SPA?

I found this code in the [Matomo Developer Guide](https://developer.matomo.org/guides/spa-tracking):

```js
window.addEventListener('hashchange', function() {
        _paq.push(['setCustomUrl', '/' + window.location.hash.substr(1)]);
        _paq.push(['setDocumentTitle', 'My New Title']);
        _paq.push(['trackPageView']);
});
```
How can use this code with your router? Could you help me?

**Comment by davidhorak** [comment]
@UIX-Design you can subscribe to the [onNavigationChanged](https://github.com/spaceavocado/svelte-router#onnavigationchanged) event and handle the _qaq.push calls inside you callback function.

**Comment by UIX-Design** [comment]
@davidhorak Could you give me a code example, how can i use it? Thanks

**Comment by davidhorak** [comment]
```
$router.onNavigationChanged((from, to) => {
        // In the case that you use history mode hash in your router: https://github.com/spaceavocado/svelte-router#create-router
        _paq.push(['setCustomUrl', '/' + to.hash]);
        // if you use history mode:
        _paq.push(['setCustomUrl', '/' + to.fullPath]);
        _paq.push(['setDocumentTitle', document.title]);
        _paq.push(['trackPageView']);
});
```

**Comment by UIX-Design** [comment]
@davidhorak thank you very much, but i get an error on console, when using your code like this:

```js
import {router} from '@spaceavocado/svelte-router';
import {ROUTER_MODE} from '@spaceavocado/svelte-router';
import {HASH_TYPE} from '@spaceavocado/svelte-router';

createRouter({
      routes: [
          {
               //Route Object
           }
      ],
      mode: 'HISTORY'
});

$router.onNavigationChanged((from, to) => {
    _paq.push(['setCustomUrl', '/' + to.fullPath]);
    _paq.push(['setDocumentTitle', document.title]);
    _paq.push(['trackPageView']);
  })
```
Error: `'router' is not a store with a 'subscribe' method` - How can i solve this?

**Comment by davidhorak** [comment]
Remove the router import, by that time it is not being initialized yet, when you want to access the router instance in the file where you initializing it, you can access it like so:

```
const router = createRouter(...);
```

Than the $router ref will work

**Comment by UIX-Design** [comment]
@davidhorak thank you, it works now, but the `document.title` will not be updated... I use the `svelte:head` in this case. When i try to log the `document.title` like this:

```js
$router.onNavigationChanged((from, to) => {
    console.log(document.title);
})
```
I get the error on console: `Uncaught TypeError: Cannot read property 'call' of undefined` - What does this mean? How can i solve this, so the title will be updated after changing a page?

**Comment by davidhorak** [comment]
@UIX-Design This does not seems to be related to the router. I would suggest debug, what exactly throws that error, and you can search also for "how to get document title in vanilla JS"
