### ISSUE TITLE
RouterLink invalid route parameters

### ISSUE THREAD

**Issue by sysmat** [spaceavocado/svelte-router#8]
I define route:

```
{
        path: "/photos/:id(\\d+)",
        name: "Photos",
        component: Photos
}
```

In Photos I define:

`export let id;`

In RouterLink  I define:

```
let photoId = 5;

<RouterLink to={{ name: 'Photos', parms: { id: photoId } }}>
          Photos
</RouterLink>

```

And routing to component Photos  not working in console is error:

`svelte-router/link, invalid route parameters, :TypeError: Expected "id" to be a string`

**Comment by sysmat** [comment]
I redefine route but still getting error:

```
{
        path: "/photos/:id(\\d+)",
        name: "PHOTOS",
        component: Photos,
        props: route => {
          return {
            id: route.params.id
          };
        }
      }

```

**Comment by davidhorak** [comment]
@sysmat just to double check:

1. You have a type here ```{{ name: 'Photos', parms: { id: photoId } }}``` **parms**
1. Are you using the latest version of the router? v1.0.16 has introduces the automatic number props parsing

**Comment by sysmat** [comment]
Yes I have

```
"devDependencies": {
    "@spaceavocado/svelte-router": "^1.0.16",
...
```

error:

`svelte-router/link, invalid route parameters, :TypeError: Expected "id" to be a string`

```
// Resolve route object to URL
  $: {
    if (tc.isObject(to)) {
      try {
        to = $router.routeURL(to);
      } catch (e) {
        console.error(`svelte-router/link, ${e.message}`);
        to = '';
      }
    }
    matchUrl = trimPrefix(to, $router.basename);
  }


```

**Comment by sysmat** [comment]
* Error in console is when app is loaded(error in createRouter )
* I'm using rollup
* So in this definition id is path parameter 
* Is it possible to have query parameters?

**Comment by davidhorak** [comment]
@sysmat so what what about the first question:

> You have a type here {{ name: 'Photos', parms: { id: photoId } }} parms

= misspelled **params**, "parms"

> Is it possible to have query parameters?  

Yes, https://github.com/spaceavocado/svelte-router#location-object
